const state = { product: "All product categories", quarter: "All quarters", country: "All countries / quota pools", sortKey: "allocation", sortDir: "desc", theme: matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light" };
let dataset = [];
const els = { productFilter: document.getElementById("productFilter"), quarterFilter: document.getElementById("quarterFilter"), countryFilter: document.getElementById("countryFilter"), tableBody: document.getElementById("tableBody"), resultCount: document.getElementById("resultCount"), kpiRows: document.getElementById("kpiRows"), kpiCurrent: document.getElementById("kpiCurrent"), kpiNext: document.getElementById("kpiNext"), kpiChanges: document.getElementById("kpiChanges"), currentTop5: document.getElementById("currentTop5"), nextTop5: document.getElementById("nextTop5"), currentQuarterLabel: document.getElementById("currentQuarterLabel"), nextQuarterLabel: document.getElementById("nextQuarterLabel"), drawer: document.getElementById("drawer"), drawerBackdrop: document.getElementById("drawerBackdrop"), drawerBody: document.getElementById("drawerBody"), drawerSubtitle: document.getElementById("drawerSubtitle") };
const fmtTonnes = value => `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value || 0)} t`;
const fmtYoY = value => value === null || value === undefined || Number.isNaN(value) ? "—" : `${value > 0 ? "+" : ""}${value.toFixed(1)}%`;
const badgeClass = value => !value ? "" : /removed|changed/i.test(value) ? "structure" : "neutral";
const yoyClass = value => value === null || value === undefined ? "neutral" : value > 0 ? "up" : value < 0 ? "down" : "neutral";
function uniqueValues(key, label) { return [label, ...new Set(dataset.map(row => row[key]).filter(Boolean))]; }
function fillSelect(element, values, current) { element.innerHTML = values.map(value => `<option value="${value}">${value}</option>`).join(""); element.value = current; }
function filteredRows() { return dataset.filter(row => (state.product === "All product categories" || row.product === state.product) && (state.quarter === "All quarters" || row.quarter === state.quarter) && (state.country === "All countries / quota pools" || row.country === state.country)); }
function sortedRows(rows) { const direction = state.sortDir === "asc" ? 1 : -1; return [...rows].sort((a, b) => { const values = { product: [a.product, b.product], quarter: [a.quarter, b.quarter], country: [a.country, b.country], allocation: [a.allocation, b.allocation], yoy: [a.yoy ?? -999, b.yoy ?? -999], duty: [Number(a.dutyRate) || 0, Number(b.dutyRate) || 0], order: [a.orderNumber || "", b.orderNumber || ""] }; const [left, right] = values[state.sortKey]; return typeof left === "number" && typeof right === "number" ? (left - right) * direction : String(left).localeCompare(String(right)) * direction; }); }
function getQuarterLabels(rows) { const quarters = [...new Set(rows.map(row => row.quarter))].sort(); return { current: quarters[0] || "2026-Q3", next: quarters[1] || "2026-Q4" }; }
function renderTop5(container, rows, label) { if (!rows.length) { container.innerHTML = `<div class="rank-card"><div class="rank-title">No rows in this filter.</div></div>`; return; } container.innerHTML = rows.slice(0, 5).map((row, index) => `<div class="rank-card" data-open-row="${row.id}"><div class="rank-top"><div><div class="rank-meta">#${index + 1} · ${label}</div><div class="rank-title">${row.country}</div></div><div class="mono">${fmtTonnes(row.allocation)}</div></div><div class="rank-meta">${row.productNo} · ${row.quotaPool}</div><div>${row.accessChange ? `<span class="badge ${badgeClass(row.accessChange)}">${row.accessChange}</span>` : `<span class="badge ${yoyClass(row.yoy)}">YoY ${fmtYoY(row.yoy)}</span>`}</div></div>`).join(""); }
function tableRow(row) { const showTip = ["FTA Quota CSQ", "FTA Quota Other countries", "Other countries"].includes(row.quotaPool); return `<tr data-open-row="${row.id}"><td>${row.productNo}<br><span class="muted">${row.product.split(" ").slice(1).join(" ")}</span></td><td class="mono">${row.quarter}</td><td><div class="country-cell"><span>${row.country}</span>${showTip ? `<span class="help">*<span class="tooltip">${row.quotaTooltip || "Add Annex-based eligibility notes here."}</span></span>` : ""}${row.accessChange ? `<span class="badge ${badgeClass(row.accessChange)}">${row.accessChange}</span>` : ""}</div><div class="muted">${row.quotaPool}</div></td><td class="mono">${fmtTonnes(row.allocation)}</td><td><span class="badge ${yoyClass(row.yoy)}">${fmtYoY(row.yoy)}</span></td><td class="mono">${row.dutyRate}</td><td class="mono">${row.orderNumber || "—"}</td></tr>`; }
function renderTable(rows) { els.tableBody.innerHTML = rows.length ? rows.map(tableRow).join("") : `<tr><td colspan="7">No rows match the current filters.</td></tr>`; }
function updateKPIs(rows) { const current = rows.filter(row => row.currentOrNext === "current"); const next = rows.filter(row => row.currentOrNext === "next"); els.kpiRows.textContent = rows.length; els.kpiCurrent.textContent = fmtTonnes(current.reduce((sum, row) => sum + (row.allocation || 0), 0)); els.kpiNext.textContent = fmtTonnes(next.reduce((sum, row) => sum + (row.allocation || 0), 0)); els.kpiChanges.textContent = rows.filter(row => row.accessChange).length; els.resultCount.textContent = `${rows.length} rows`; }
function renderDashboard() { const rows = sortedRows(filteredRows()); const { current, next } = getQuarterLabels(rows); els.currentQuarterLabel.textContent = current; els.nextQuarterLabel.textContent = next; renderTop5(els.currentTop5, rows.filter(row => row.quarter === current).sort((a, b) => b.allocation - a.allocation), current); renderTop5(els.nextTop5, rows.filter(row => row.quarter === next).sort((a, b) => b.allocation - a.allocation), next); renderTable(rows); updateKPIs(rows); }
function openDrawer(id) { const row = dataset.find(item => item.id === Number(id)); if (!row) return; document.getElementById("drawerTitle").textContent = row.country; els.drawerSubtitle.textContent = `${row.productNo} · ${row.quarter} · ${row.quotaPool}`; els.drawerBody.innerHTML = `<div>${row.accessChange ? `<span class="badge ${badgeClass(row.accessChange)}">${row.accessChange}</span>` : `<span class="badge neutral">Comparable quota path</span>`}</div><p class="muted">${row.notes || ""}</p><div class="detail-grid"><div class="detail-card"><div class="detail-label">Allocated quota</div><div class="detail-value mono">${fmtTonnes(row.allocation)}</div></div><div class="detail-card"><div class="detail-label">Prior-year quarter</div><div class="detail-value mono">${row.compareQuarter || "—"}</div></div><div class="detail-card"><div class="detail-label">Prior-year allocation</div><div class="detail-value mono">${row.priorAllocation ? fmtTonnes(row.priorAllocation) : "—"}</div></div><div class="detail-card"><div class="detail-label">Additional duty</div><div class="detail-value mono">${row.dutyRate}</div></div><div class="detail-card"><div class="detail-label">Order number</div><div class="detail-value mono">${row.orderNumber || "—"}</div></div><div class="detail-card"><div class="detail-label">Quota pool</div><div class="detail-value">${row.quotaPool}</div></div></div><div><div class="detail-label">Quota-pool note</div><div class="detail-value">${row.quotaTooltip || ""}</div></div>`; els.drawer.classList.add("open"); els.drawerBackdrop.classList.add("open"); els.drawer.setAttribute("aria-hidden", "false"); }
function closeDrawer() { els.drawer.classList.remove("open"); els.drawerBackdrop.classList.remove("open"); els.drawer.setAttribute("aria-hidden", "true"); }
function initFilters() { fillSelect(els.productFilter, uniqueValues("product", "All product categories"), state.product); fillSelect(els.quarterFilter, uniqueValues("quarter", "All quarters"), state.quarter); fillSelect(els.countryFilter, uniqueValues("country", "All countries / quota pools"), state.country); }
function setTheme(theme) { state.theme = theme; document.documentElement.setAttribute("data-theme", theme); document.getElementById("themeToggle").textContent = theme === "dark" ? "Light mode" : "Dark mode"; }
async function loadDataset() { const response = await fetch("./data.json"); if (!response.ok) throw new Error("Failed to load data.json"); dataset = await response.json(); }
document.getElementById("themeToggle").addEventListener("click", () => setTheme(state.theme === "dark" ? "light" : "dark"));
document.getElementById("resetFilters").addEventListener("click", () => { state.product = "All product categories"; state.quarter = "All quarters"; state.country = "All countries / quota pools"; state.sortKey = "allocation"; state.sortDir = "desc"; initFilters(); renderDashboard(); });
[els.productFilter, els.quarterFilter, els.countryFilter].forEach((element, index) => element.addEventListener("change", event => { if (index === 0) state.product = event.target.value; if (index === 1) state.quarter = event.target.value; if (index === 2) state.country = event.target.value; renderDashboard(); }));
document.querySelectorAll("[data-sort]").forEach(button => button.addEventListener("click", () => { const key = button.dataset.sort; if (state.sortKey === key) state.sortDir = state.sortDir === "asc" ? "desc" : "asc"; else { state.sortKey = key; state.sortDir = ["product", "quarter", "country", "order"].includes(key) ? "asc" : "desc"; } renderDashboard(); }));
document.addEventListener("click", event => { const target = event.target.closest("[data-open-row]"); if (target) openDrawer(target.dataset.openRow); });
document.getElementById("closeDrawer").addEventListener("click", closeDrawer); els.drawerBackdrop.addEventListener("click", closeDrawer); document.addEventListener("keydown", event => { if (event.key === "Escape") closeDrawer(); });
(async () => { setTheme(state.theme); await loadDataset(); initFilters(); renderDashboard(); })().catch(error => { console.error(error); alert("Failed to load dashboard data. Check data.json path and file contents."); });
